name: Detect change in file version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare states
        id: compare_states
        run: |
          reference_state=$(cat reference_state.txt)
          current_state=$(cat package.json)

          echo "Reference state:"
          echo "$reference_state"
          echo "Current state:"
          echo "$current_state"

          if [ "$reference_state" != "$current_state" ]; then
            echo "File has been modified"
            exit 1
          else
            echo "File has not been modified"
          fi

      - name: Create HTML Page
        run: |
          echo '<!DOCTYPE html>' > logs.html
          echo '<html>' >> logs.html
          echo '<head>' >> logs.html
          echo '    <title>Compare States Logs</title>' >> logs.html
          echo '</head>' >> logs.html
          echo '<body>' >> logs.html
          echo '    <h1>Compare States Logs</h1>' >> logs.html
          echo '    <pre>' >> logs.html
          echo '        <!-- Paste the logs here -->' >> logs.html
          echo "        ${{ steps.compare_states.outputs.logs }}" >> logs.html
          echo '    </pre>' >> logs.html
          echo '</body>' >> logs.html
          echo '</html>' >> logs.html

      - name: Deploy Logs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main
          commit_message: "Publish Compare States Logs"
