name: Detect change in file version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get reference state of package.json
        id: get_reference_state
        run: echo "::set-output name=reference_state::$(cat reference_state.txt)"

      - name: Get current state of package.json
        id: get_current_state
        run: echo "::set-output name=current_state::$(cat package.json)"

      - name: Compare states
        id: compare_states
        run: |
          reference_state=${{ steps.get_reference_state.outputs.reference_state }}
          current_state=${{ steps.get_current_state.outputs.current_state }}

          if [ "$(jq -n --arg reference "$reference_state" --arg current "$current_state" '$reference != $current')" != "" ]; then
            echo "Change detected"
            exit 1
          fi


      - name: Deploy file to GitHub Pages
        if: steps.compare_states.outputs.compare_states == 'Change detected'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: package.json

