name: Detect change in file version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare states
        id: compare_states
        run: |
          reference_state=$(cat reference_state.txt)
          current_state=$(cat package.json)

          echo "Reference state:"
          echo "$reference_state"
          echo "Current state:"
          echo "$current_state"

          if [ "$reference_state" != "$current_state" ]; then
            echo "File has been modified" >> comparison_result.txt
            exit 1
          else
            echo "File has not been modified" >> comparison_result.txt
          fi
          
      - name: Deploy Logs to GitHub Pages
        if: steps.compare_states.outputs.compare_states == 'File has been modified' || steps.compare_states.outputs.compare_states == 'File has not been modified'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          commit_message: "Publish Compare States Logs"
