name: Detect change in file version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get previous modification timestamp
        id: get_previous_timestamp
        run: echo "::set-output name=timestamp::$(cat previous_timestamp.txt)"

      - name: Get current modification timestamp
        id: get_current_timestamp
        run: echo "::set-output name=timestamp::$(stat -c %Y package.json)"

      - name: Check if file version has changed
        run: |
          previous_timestamp=${{ steps.get_previous_timestamp.outputs.timestamp }}
          current_timestamp=${{ steps.get_current_timestamp.outputs.timestamp }}

          if [ $current_timestamp -gt $previous_timestamp ]; then
            echo "Change detected"
          else
            echo "No change detected"
          fi
        id: check_version

      - name: Save current modification timestamp
        run: |
          echo "::set-output name=timestamp::$(stat -c %Y package.json)" > current_timestamp.txt
          mv current_timestamp.txt previous_timestamp.txt

      - name: Deploy file to GitHub Pages
        if: steps.check_version.outputs.check_version == 'Change detected'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: package.json

